#!/bin/sh

# scripts/update:
#   Resolve all dependencies that the application requires to run.

set -e

cd "$(dirname "$0")/.."

echo "==> Updating backend assets..."
(
  set -e
  ./activator update
)
echo "==> Done!"

echo ""
echo "==> Updating client-side assets..."
(
  set -e
  cd client
  npm install
)
echo "==> Done!"
